import type { NextPage } from "next";
import Head from "next/head";
import { Profile } from "../components/Profile";

const Home: NextPage = (): JSX.Element => {
  return (
    <div>
      <Head>
        <title>Personal Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={"/favicon.ico"} />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200"
          rel="stylesheet"
        />
        <link
          href={
            "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
          }
          rel="stylesheet"
        />
      </Head>
      <body>
        <Profile />
      </body>
    </div>
  );
};

export default Home;
